apiVersion: apps/v1
kind: Deployment
metadata:
  name: Leumi-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchlabels:
      app: webapp
  template:
    metadata:
      labels: 
        app: webapp    
    spec:
      containers:
      - name: jenkinserver
        image: yossid4/webapp:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443